development:
  adapter: postgresql
  encoding: utf8
  database: hackthon_site_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: hackthon_site_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: hackthon_site_production
  pool: 5
