# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 310241211062a73f1e10d112517ec935b1417acfcc205d40f1e875745d38faada75b1b968346017b75c9a555ae967be2974337a78305c6f63db886c6e57e24f3

test:
  secret_key_base: 673713b0b7a35199cfa417df04057e86e3c754eda335e2020a5d1049f608ab003cf105957826aa6d14059d01a57358116a3e2e145f0c72babac39697d111e97d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
